# Site settings
author: Henna Vahatiitto
title: Journey to Web Developing
header-img: img/home-bg.png
email: hnnamv@gmail.com
copyright_name: Henna Vahatiitto
description: > # this means to ignore newlines until "baseurl:"
  Recording and reflecting on my journey through web development course
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bvmbie

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
